import type { TripForm, BoardType, TripStatus } from "./types";

export const surfSpots = [
  "沙崙白沙灣",
  "餐廳",
  "金山",
  "翡翠灣",
  "萬里",
  "福隆",
  "大溪",
  "梗枋",
  "雙獅",
  "外澳",
  "烏石港（北堤）",
  "烏石港（南堤）",
  "臭水",
  "竹安清水",
  "蘇澳 - 無尾港",
  "環保公園",
  "花蓮北濱",
  "雙橋",
  "鹽寮漁港",
  "磯崎",
  "八仙洞",
  "宜灣成功",
  "都歷東河",
  "金樽",
  "都蘭",
  "台東",
  "九棚",
  "佳樂水",
  "南灣",
  "射寮",
  "旗津",
  "漁光島（馬場）",
  "四草橋",
  "山水",
  "松柏港",
  "外埔漁港",
  "竹南",
];

export const defaultTripForm: TripForm = {
  date: "",
  destination: "烏石港（北堤）",
  departureArea: "",
  exactPickup: "",
  route: "",
  pickupMode: true,
  tripType: "去回程",
  departureMode: "準時出發",
  departureTime: "06:00",
  returnMode: "現場討論",
  returnTime: "14:00",
  maxPassengers: 3,
  shortboards: 0,
  longboards: 0,
  boardLocation: "都可",
  vehicle: "",
  price: 200,
  rules: [],
  note: "",
};

export const boardLabel: Record<BoardType, string> = {
  none: "無板",
  short: "短板",
  long: "長板",
};

export const statusLabel: Record<TripStatus, string> = {
  open: "開放共乘",
  full: "已額滿",
  departed: "已出發",
  completed: "已完成",
  cancelled: "已取消",
};
